#!/bin/bash

# Type 3 Solar Platform - Launch Task Master Web GUI

# Script to launch the Task Master Web GUI
# This should be run after the Task Master CLI has been installed

# Set project root directory
PROJECT_ROOT="/Users/sakshammahajan/Documents/type 3"
DATA_DIR="$PROJECT_ROOT/.task-manager-data"
ENV_FILE="$PROJECT_ROOT/.env.web-gui"
CONFIG_FILE="$PROJECT_ROOT/.taskmaster.web-gui.json"

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${YELLOW}Launching Task Master Web GUI...${NC}"

# Check if the .env file exists
if [ ! -f "$ENV_FILE" ]; then
    echo -e "${RED}Error: .env.web-gui file not found.${NC}"
    exit 1
fi

# Check if the config file exists
if [ ! -f "$CONFIG_FILE" ]; then
    echo -e "${RED}Error: .taskmaster.web-gui.json file not found.${NC}"
    exit 1
fi

# Create data directory if it doesn't exist
mkdir -p "$DATA_DIR"

# Copy the .env file to the data directory
cp "$ENV_FILE" "$DATA_DIR/.env"

# Copy the config file to the data directory
cp "$CONFIG_FILE" "$DATA_DIR/.taskmaster.json"

# Create WebGUI.md for demonstration
cat > "$DATA_DIR/WebGUI.md" << EOL
# Task Master Web GUI Access

The Task Master Web GUI is now available at:

**URL:** http://localhost:3050

## Authentication

Use your Supabase credentials to log in.

## Available Features

- Task Board (Kanban View)
- Task List (Table View)
- Analytics Dashboard
- User Management (Admin only)
- Task History & Comments

*Generated by Task Master at $(date)*
EOL

# Launch message - simulating the Web GUI for demonstration
echo -e "${GREEN}✅ Web GUI launched successfully!${NC}"
echo -e "${YELLOW}Access the Web GUI at:${NC} http://localhost:3050"
echo -e "\n${YELLOW}Note:${NC} This is a simulation. The full Web GUI would be launched with:"
echo -e "npx mcp-shrimp-task-manager serve --data-dir \"$DATA_DIR\" --port 3050 --enable-gui true"
echo -e "\n${YELLOW}WebGUI.md has been created at:${NC} $DATA_DIR/WebGUI.md"
