[build]
  publish = "dist"
  command = "npm run build"

# First, handle all static assets BEFORE the SPA catch-all
[[redirects]]
  from = "/_assets/*"
  to = "/_assets/:splat"
  status = 200

# Then handle the SPA routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Set cache headers for static assets
[[headers]]
  for = "/_assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Explicit MIME type for JavaScript files
[[headers]]
  for = "/_assets/js/*"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Set security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Less restrictive CSP to allow all required resources
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:;"
