-- Product SKUs Insertion SQL Script
-- Generated for Type 3 Solar Platform

-- On-Grid Solar Systems
INSERT INTO product_skus (name, sku, category, price, capacity_kw, description, specifications, inventory_count, generation, area_required, monthly_savings, subsidy_amount, original_price, panel_type, installation_time, image_url, features)
VALUES
('1 kW On-Grid Solar System', 'APN-ONGRID-1KW', 'on-grid', 45000, 1.0, 'Complete 1 kW on-grid solar system for residential use with high efficiency panels.', '{"panels": "4 x 250W monocrystalline", "inverter": "1 kW grid-tied", "warranty": "25 years", "efficiency": "21%"}', 10, '1st Generation', 100, 1250, 30000, 75000, 'monocrystalline', '1-2 days', 'https://images.unsplash.com/photo-1509391366360-2e959784a276?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Subsidy eligible", "Grid-connected", "No batteries required", "Simple installation", "Remote monitoring"]'),

('2 kW On-Grid Solar System', 'APN-ONGRID-2KW', 'on-grid', 90000, 2.0, 'Complete 2 kW on-grid solar system for residential use with high efficiency panels.', '{"panels": "8 x 250W monocrystalline", "inverter": "2 kW grid-tied", "warranty": "25 years", "efficiency": "21%"}', 8, '1st Generation', 200, 2500, 60000, 150000, 'monocrystalline', '2-3 days', 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Subsidy eligible", "Grid-connected", "No batteries required", "Simple installation", "Remote monitoring"]'),

('3 kW On-Grid Solar System', 'APN-ONGRID-3KW', 'on-grid', 137000, 3.0, 'Complete 3 kW on-grid solar system for residential use with high efficiency panels.', '{"panels": "12 x 250W monocrystalline", "inverter": "3 kW grid-tied", "warranty": "25 years", "efficiency": "21%"}', 6, '1st Generation', 300, 3750, 78000, 215000, 'monocrystalline', '3-4 days', 'https://images.unsplash.com/photo-1595437193398-f24279553f4f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Subsidy eligible", "Grid-connected", "No batteries required", "Simple installation", "Remote monitoring"]'),

('5 kW On-Grid Solar System', 'APN-ONGRID-5KW', 'on-grid', 272000, 5.0, 'Complete 5 kW on-grid solar system for commercial use with high efficiency panels.', '{"panels": "20 x 250W monocrystalline", "inverter": "5 kW grid-tied", "warranty": "25 years", "efficiency": "21%"}', 5, '1st Generation', 500, 6250, 78000, 350000, 'monocrystalline', '4-5 days', 'https://images.unsplash.com/photo-1592833167665-45638961c614?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Subsidy eligible", "Grid-connected", "No batteries required", "Simple installation", "Remote monitoring"]'),

('10 kW On-Grid Solar System', 'APN-ONGRID-10KW', 'on-grid', 572000, 10.0, 'Complete 10 kW on-grid solar system for commercial use with high efficiency panels.', '{"panels": "40 x 250W monocrystalline", "inverter": "10 kW grid-tied", "warranty": "25 years", "efficiency": "21%"}', 3, '1st Generation', 1000, 12500, 78000, 650000, 'monocrystalline', '7-10 days', 'https://images.unsplash.com/photo-1623227713723-2970e0f17eca?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Subsidy eligible", "Grid-connected", "No batteries required", "Simple installation", "Remote monitoring"]'),

('20 kW On-Grid Solar System', 'APN-ONGRID-20KW', 'on-grid', 940000, 20.0, 'Complete 20 kW on-grid solar system for industrial use with high efficiency panels.', '{"panels": "80 x 250W monocrystalline", "inverter": "20 kW grid-tied", "warranty": "25 years", "efficiency": "21%"}', 2, '1st Generation', 2000, 25000, 0, 940000, 'monocrystalline', '14-20 days', 'https://images.unsplash.com/photo-1605980776566-0486cda076e5?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Grid-connected", "No batteries required", "Advanced monitoring", "Industrial grade components", "Professional installation required"]');

-- Off-Grid Solar Systems
INSERT INTO product_skus (name, sku, category, price, capacity_kw, description, specifications, inventory_count, generation, area_required, monthly_savings, subsidy_amount, original_price, panel_type, installation_time, image_url, features)
VALUES
('1 kW Off-Grid Solar System', 'APN-OFFGRID-1KW', 'off-grid', 100000, 1.0, 'Complete 1 kW off-grid solar system with battery backup for areas with unreliable grid power.', '{"panels": "4 x 250W monocrystalline", "inverter": "1 kW off-grid", "batteries": "1.5 kWh lithium-ion", "warranty": "25 years panels, 10 years battery", "efficiency": "21%"}', 8, '2nd Generation', 120, 1000, 0, 100000, 'monocrystalline', '2-3 days', 'https://images.unsplash.com/photo-1521618755572-156ae0cdd74d?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Battery backup 4-6 hours", "Works during power outages", "Zero electricity bills", "Remote monitoring", "Expandable capacity"]'),

('2 kW Off-Grid Solar System', 'APN-OFFGRID-2KW', 'off-grid', 175000, 2.0, 'Complete 2 kW off-grid solar system with extended battery backup for areas with unreliable grid power.', '{"panels": "8 x 250W monocrystalline", "inverter": "2 kW off-grid", "batteries": "3 kWh lithium-ion", "warranty": "25 years panels, 10 years battery", "efficiency": "21%"}', 6, '2nd Generation', 240, 2000, 0, 175000, 'monocrystalline', '3-4 days', 'https://images.unsplash.com/photo-1454779132693-e5cd0a216ed3?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Battery backup 6-8 hours", "Works during power outages", "Zero electricity bills", "Remote monitoring", "Expandable capacity"]'),

('3 kW Off-Grid Solar System', 'APN-OFFGRID-3KW', 'off-grid', 250000, 3.0, 'Complete 3 kW off-grid solar system with substantial battery backup for extended power outages.', '{"panels": "12 x 250W monocrystalline", "inverter": "3 kW off-grid", "batteries": "4.5 kWh lithium-ion", "warranty": "25 years panels, 10 years battery", "efficiency": "21%"}', 4, '2nd Generation', 360, 3000, 0, 250000, 'monocrystalline', '4-5 days', 'https://images.unsplash.com/photo-1566093097221-ac2335b09e70?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Battery backup 8-10 hours", "Works during power outages", "Zero electricity bills", "Remote monitoring", "Expandable capacity"]'),

('5 kW Off-Grid Solar System', 'APN-OFFGRID-5KW', 'off-grid', 400000, 5.0, 'Complete 5 kW off-grid solar system for businesses and larger homes with significant power requirements.', '{"panels": "20 x 250W monocrystalline", "inverter": "5 kW off-grid", "batteries": "7.5 kWh lithium-ion", "warranty": "25 years panels, 10 years battery", "efficiency": "21%"}', 3, '2nd Generation', 600, 5000, 0, 400000, 'monocrystalline', '6-8 days', 'https://images.unsplash.com/photo-1509391366360-2e959784a276?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Battery backup 10-12 hours", "Works during power outages", "Zero electricity bills", "Remote monitoring", "Expandable capacity"]');

-- Hybrid Solar Systems
INSERT INTO product_skus (name, sku, category, price, capacity_kw, description, specifications, inventory_count, generation, area_required, monthly_savings, subsidy_amount, original_price, panel_type, installation_time, image_url, features)
VALUES
('1 kW Hybrid Solar System', 'APN-HYBRID-1KW', 'hybrid', 120000, 1.0, 'Advanced 1 kW hybrid solar system that works both on-grid and off-grid with seamless switching.', '{"panels": "4 x 250W monocrystalline", "inverter": "1 kW hybrid", "batteries": "1.5 kWh lithium-ion", "warranty": "25 years panels, 10 years battery", "efficiency": "21%"}', 7, '3rd Generation', 120, 1250, 0, 120000, 'monocrystalline', '2-3 days', 'https://images.unsplash.com/photo-1613665813446-82a78f00e2ed?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Grid-connected with battery backup", "Automatic switchover during outages", "Smart energy management", "Mobile app control", "Export excess power to grid"]'),

('2 kW Hybrid Solar System', 'APN-HYBRID-2KW', 'hybrid', 200000, 2.0, 'Advanced 2 kW hybrid solar system that works both on-grid and off-grid with seamless switching and extended backup.', '{"panels": "8 x 250W monocrystalline", "inverter": "2 kW hybrid", "batteries": "3 kWh lithium-ion", "warranty": "25 years panels, 10 years battery", "efficiency": "21%"}', 6, '3rd Generation', 240, 2500, 0, 200000, 'monocrystalline', '3-4 days', 'https://images.unsplash.com/photo-1592833167665-45638961c614?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Grid-connected with battery backup", "Automatic switchover during outages", "Smart energy management", "Mobile app control", "Export excess power to grid"]');

-- Solar Fencing Systems
INSERT INTO product_skus (name, sku, category, price, capacity_kw, description, specifications, inventory_count, generation, area_required, monthly_savings, subsidy_amount, original_price, panel_type, installation_time, image_url, features)
VALUES
('100m Solar Electric Fence', 'APN-FENCE-100M', 'fencing', 25000, 0.1, 'Solar-powered electric fencing system covering 100 meters, ideal for small properties and farms.', '{"coverage": "100 meters", "energizer": "Single unit", "voltage": "7000-9000V", "solar panel": "20W", "battery backup": "24 hours"}', 10, '1st Generation', 10, 0, 0, 25000, 'polycrystalline', '1 day', 'https://images.unsplash.com/photo-1523626797181-8c5ae80d40c2?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Single energizer unit", "Weatherproof design", "Basic security setup", "Includes warning signs", "Easy DIY installation"]'),

('500m Solar Electric Fence', 'APN-FENCE-500M', 'fencing', 90000, 0.2, 'Advanced solar-powered electric fencing system covering 500 meters with fault detection.', '{"coverage": "500 meters", "energizer": "Dual units", "voltage": "8000-10000V", "solar panel": "50W", "battery backup": "48 hours"}', 6, '2nd Generation', 20, 0, 0, 90000, 'polycrystalline', '2-3 days', 'https://images.unsplash.com/photo-1560204957-bb05676adb28?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Dual energizer system", "Fault detection technology", "Remote monitoring capability", "Siren alarm option", "Professional installation recommended"]');

-- Solar Street Lights
INSERT INTO product_skus (name, sku, category, price, capacity_kw, description, specifications, inventory_count, generation, area_required, monthly_savings, subsidy_amount, original_price, panel_type, installation_time, image_url, features)
VALUES
('20W Solar Street Light', 'APN-SSL-20W', 'lighting', 6800, 0.02, 'Compact 20W solar street light with motion sensor, ideal for pathways and small areas.', '{"wattage": "20W", "lumens": "2000lm", "battery": "LiFePO4 20Ah", "height": "4-5 meters", "operation": "Dusk to dawn + motion sensing"}', 20, '1st Generation', 1, 150, 0, 6800, 'polycrystalline', '2-3 hours', 'https://images.unsplash.com/photo-1617881770125-6fb0d039ecad?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Motion sensing", "Dusk to dawn operation", "3 days battery backup", "Die-cast aluminum body", "2 year warranty"]'),

('50W Solar Street Light', 'APN-SSL-50W', 'lighting', 18900, 0.05, 'High-performance 50W solar street light for commercial areas and larger spaces.', '{"wattage": "50W", "lumens": "5400lm", "battery": "LiFePO4 65Ah", "height": "8-10 meters", "operation": "Dusk to dawn + motion sensing + timer"}', 12, '2nd Generation', 2, 400, 0, 18900, 'monocrystalline', '4-5 hours', 'https://images.unsplash.com/photo-1611292995678-b8f418b353e1?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Motion sensing with time control", "Dusk to dawn operation", "5 days battery backup", "Die-cast aluminum body", "5 year warranty", "Remote monitoring capability"]');

-- Solar Water Heaters
INSERT INTO product_skus (name, sku, category, price, capacity_kw, description, specifications, inventory_count, generation, area_required, monthly_savings, subsidy_amount, original_price, panel_type, installation_time, image_url, features)
VALUES
('100 LPD Solar Water Heater', 'APN-SWH-100LPD', 'water_heating', 28000, 0.0, 'Compact 100 LPD solar water heater ideal for small families (2-3 members).', '{"capacity": "100 LPD", "collector_area": "2 sq.m", "tank_material": "Stainless Steel 304", "insulation": "PUF 50mm", "collector_type": "Evacuated Tube"}', 10, '1st Generation', 5, 600, 0, 28000, 'evacuated_tube', '4-6 hours', 'https://images.unsplash.com/photo-1611834422752-13b5be5e98dc?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["100 liters capacity", "Suitable for 2-3 people", "Hot water up to 80°C", "5 year warranty", "Stainless steel construction"]'),

('200 LPD Solar Water Heater', 'APN-SWH-200LPD', 'water_heating', 38000, 0.0, 'Medium-sized 200 LPD solar water heater perfect for regular families (3-5 members).', '{"capacity": "200 LPD", "collector_area": "4 sq.m", "tank_material": "Stainless Steel 304", "insulation": "PUF 50mm", "collector_type": "Evacuated Tube"}', 8, '1st Generation', 8, 1200, 0, 38000, 'evacuated_tube', '6-8 hours', 'https://images.unsplash.com/photo-1611834318857-33cd7de05a12?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["200 liters capacity", "Suitable for 3-5 people", "Hot water up to 80°C", "7 year warranty", "Stainless steel construction"]');

-- Solar Water Pumps
INSERT INTO product_skus (name, sku, category, price, capacity_kw, description, specifications, inventory_count, generation, area_required, monthly_savings, subsidy_amount, original_price, panel_type, installation_time, image_url, features)
VALUES
('1 HP Solar Water Pump', 'APN-SWP-1HP', 'water_pumping', 100000, 0.75, 'Efficient 1 HP solar water pump system for small farms and domestic use.', '{"capacity": "1 HP", "flow_rate": "90-150 LPM", "head": "50-100 feet", "panel_capacity": "1.1 kW", "controller": "MPPT with VFD"}', 8, '2nd Generation', 10, 1500, 0, 100000, 'polycrystalline', '1 day', 'https://images.unsplash.com/photo-1531022385644-064d7d273c38?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["1 HP AC submersible pump", "MPPT controller with VFD", "Suitable for irrigation and domestic use", "Remote monitoring optional", "5 year warranty"]'),

('2 HP Solar Water Pump', 'APN-SWP-2HP', 'water_pumping', 170000, 1.5, 'Powerful 2 HP solar water pump system for medium farms and housing complexes.', '{"capacity": "2 HP", "flow_rate": "150-200 LPM", "head": "100-150 feet", "panel_capacity": "2.2 kW", "controller": "MPPT with VFD"}', 6, '2nd Generation', 18, 3000, 0, 170000, 'polycrystalline', '1-2 days', 'https://images.unsplash.com/photo-1552252662-5fc5e7e84fa6?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["2 HP AC submersible pump", "MPPT controller with VFD", "Suitable for medium farms", "Remote monitoring included", "5 year warranty"]');

-- Solar Rock Lights
INSERT INTO product_skus (name, sku, category, price, capacity_kw, description, specifications, inventory_count, generation, area_required, monthly_savings, subsidy_amount, original_price, panel_type, installation_time, image_url, features)
VALUES
('Solar Rock Light', 'APN-SRL-ROCK', 'rock_lighting', 450, 0.002, 'Decorative solar-powered rock light for garden pathways and landscaping.', '{"wattage": "2W", "lumens": "100lm", "battery": "1500mAh", "operation": "8-10 hours", "material": "Resin composite"}', 50, '1st Generation', 0.1, 20, 0, 450, 'polycrystalline', 'Plug and play', 'https://images.unsplash.com/photo-1558954350-2bc9da161c7c?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Rock-shaped design", "Weatherproof IP65", "Warm white LED", "Auto on/off at dusk/dawn", "No wiring required"]'),

('Solar Ice Cube Light', 'APN-SRL-CUBE', 'rock_lighting', 550, 0.003, 'Modern solar-powered ice cube light for contemporary garden designs and path lighting.', '{"wattage": "3W", "lumens": "150lm", "battery": "2000mAh", "operation": "10-12 hours", "material": "Frosted glass"}', 40, '2nd Generation', 0.1, 25, 0, 550, 'polycrystalline', 'Plug and play', 'https://images.unsplash.com/photo-1563425612-035e967c77a9?ixlib=rb-1.2.1&auto=format&fit=crop&w=1000&q=80', '["Ice cube design", "Weatherproof IP67", "RGB color changing", "Auto on/off at dusk/dawn", "No wiring required"]');
